pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'myapp'
        DOCKER_REGISTRY = 'docker.io/nayan1103'
        K8S_NAMESPACE = 'default'

        DOCKER_USERNAME = credentials('docker-username')
        DOCKER_PASSWORD = credentials('docker-password')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/nayanacharya7/github-action-test.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${BUILD_ID} .'
            }
        }

        stage('Push to Docker Registry') {
            steps {
                sh """
                echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${BUILD_ID}
                """
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                kubectl config use-context docker-desktop
                kubectl set image deployment/your-deployment-name ${DOCKER_IMAGE_NAME}=${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${BUILD_ID} -n ${K8S_NAMESPACE}
                kubectl rollout status deployment/your-deployment-name -n ${K8S_NAMESPACE}
                """
            }
        }
    }
}
